[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"


[project]
name = "mcp-details"
version = "0.0.0"
description = "A learning project for non-executing inspection of MCP servers."
dependencies = [
    "mcp==2.1.1",
]

[project.optional-dependencies]
test = [
    "pytest",
]


[tool.setuptools.packages.find]
where = ["src"]


[tool.pytest.ini_options]
testpaths = ["tests"]